// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1OpjjOp4QrQUJqRTCFt92vSxofG4lLMo',
    appId: '1:304528360280:web:3f7fb76091361655ac1b2d',
    messagingSenderId: '304528360280',
    projectId: 'ecommerce-laza-app',
    authDomain: 'ecommerce-laza-app.firebaseapp.com',
    storageBucket: 'ecommerce-laza-app.firebasestorage.app',
    measurementId: 'G-6Z2F8ZQ6E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hC5IHM4FTP0owSqk4e6qQTb-7edAdrg',
    appId: '1:304528360280:android:969bfb5280ba2abfac1b2d',
    messagingSenderId: '304528360280',
    projectId: 'ecommerce-laza-app',
    storageBucket: 'ecommerce-laza-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxUugkF_z86bhShUO9ax2s66K5PlgavQ',
    appId: '1:304528360280:ios:fad062827765c79bac1b2d',
    messagingSenderId: '304528360280',
    projectId: 'ecommerce-laza-app',
    storageBucket: 'ecommerce-laza-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxUugkF_z86bhShUO9ax2s66K5PlgavQ',
    appId: '1:304528360280:ios:fad062827765c79bac1b2d',
    messagingSenderId: '304528360280',
    projectId: 'ecommerce-laza-app',
    storageBucket: 'ecommerce-laza-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1OpjjOp4QrQUJqRTCFt92vSxofG4lLMo',
    appId: '1:304528360280:web:5ad4eb7d82446f62ac1b2d',
    messagingSenderId: '304528360280',
    projectId: 'ecommerce-laza-app',
    authDomain: 'ecommerce-laza-app.firebaseapp.com',
    storageBucket: 'ecommerce-laza-app.firebasestorage.app',
    measurementId: 'G-0VMCYWMNBL',
  );
}
